# -*- coding: utf-8 -*-
"""Projeto_Salah_Son

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1euq2tBQ1lPZAtX-J36dftIy10V83YQd9

#Comparando Salah x Son temporada 21/22

Estudo criado para comparar as estatíscas de Son e Salah, na temporada de 21/22

GLOSSÁRIO 

A:assistências

CA:Cartões amarelos

CG:Chutes a gol

CV:Cartões Vermelhos

FC:Faltas cometidas

FS:Faltas sofridas

G:Total de gols

I:Impedimentos

PG:Porcentagens de gols

F:Finalizações

##Mohamed Salah
"""

import pandas as pd
  import seaborn as sns

data1 = pd.read_html('https://www.espn.com.br/futebol/jogador/jogos/_/id/173896/time/364/tipo/eng.1/ano/2021')
data1

salah = data1[0]
salah.head()

salah.rename(columns = {'Date' : 'Data', 'TC' : 'F'}, inplace = True)

salah.head()

print('O máximo de gols em uma partida foi de', salah.G.max())

print('Total de',salah.shape[0], 'jogos')

salah['PG'] = (salah['G'] / salah['FS']).round(2)
salah

"""##Son Heung-Min"""

data2 = pd.read_html('https://www.espn.com.br/futebol/jogador/jogos/_/id/149945/time/367/tipo/eng.1/ano/2021')
data2

son = data2[0]
son.head()

"""##Salah x Son

"""

salah['CG'].sum()

son['CG'].sum()t

ax = sns.relplot(x='G', y = 'FS', kind = 'line', data = salah)
ax = sns.relplot(x='G', y = 'FS', kind = 'line', data = son)

